# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templadesui/formcarregafoto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1563, 765)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconegeral/icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QMessageBox QLabel{\n"
"\n"
"\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 0, 0);\n"
"\n"
"}\n"
"QMessageBox QPushButton{\n"
"background-color: rgb(103, 255, 128);font: 87 14pt Arial;\n"
"\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.bt_visular_pasta = QtWidgets.QPushButton(self.frame_3)
        self.bt_visular_pasta.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_visular_pasta.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconegeral/icons/book_previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_visular_pasta.setIcon(icon1)
        self.bt_visular_pasta.setIconSize(QtCore.QSize(60, 60))
        self.bt_visular_pasta.setCheckable(True)
        self.bt_visular_pasta.setObjectName("bt_visular_pasta")
        self.horizontalLayout_4.addWidget(self.bt_visular_pasta)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.frame_pastas = QtWidgets.QFrame(self.frame_2)
        self.frame_pastas.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_pastas.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_pastas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pastas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pastas.setObjectName("frame_pastas")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_pastas)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pasta = QtWidgets.QTreeView(self.frame_pastas)
        self.pasta.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pasta.setObjectName("pasta")
        self.pasta.header().setDefaultSectionSize(450)
        self.horizontalLayout_3.addWidget(self.pasta)
        self.horizontalLayout_2.addWidget(self.frame_pastas)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.bt_Visualisar = QtWidgets.QPushButton(self.frame)
        self.bt_Visualisar.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_Visualisar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bt_Visualisar.setFont(font)
        self.bt_Visualisar.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconegeral/icons/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Visualisar.setIcon(icon2)
        self.bt_Visualisar.setIconSize(QtCore.QSize(60, 60))
        self.bt_Visualisar.setObjectName("bt_Visualisar")
        self.horizontalLayout.addWidget(self.bt_Visualisar)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Carregar Fotos"))
        self.bt_visular_pasta.setText(_translate("Form", "View Path"))
        self.lineEdit.setToolTip(_translate("Form", "copy and paste path / Copie e cole aqui caminho"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Copy and paste path"))
        self.bt_Visualisar.setText(_translate("Form", "View"))
import iconesform_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
