# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templadesui/formcarregafoto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1352, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1352, 1080))
        Form.setSizeIncrement(QtCore.QSize(0, 10))
        Form.setBaseSize(QtCore.QSize(0, 10))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/icons/cil-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget{\n"
"background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QMessageBox QLabel{\n"
"\n"
"\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"    color: white;\n"
"\n"
"}\n"
"QMessageBox QPushButton{\n"
"background-color: rgb(103, 255, 128);font: 87 14pt Arial;\n"
"\n"
"}\n"
"QMenu::item {\n"
"    padding: 2px 25px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_qmenu2 = QtWidgets.QFrame(Form)
        self.frame_qmenu2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_qmenu2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_qmenu2.setStyleSheet("QPushButton{\n"
"border:none;}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 170, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 137, 206);\n"
"}")
        self.frame_qmenu2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_qmenu2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_qmenu2.setObjectName("frame_qmenu2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_qmenu2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labe_icon_sobre = QtWidgets.QLabel(self.frame_qmenu2)
        self.labe_icon_sobre.setText("")
        self.labe_icon_sobre.setPixmap(QtGui.QPixmap(":/icone/icons/cil-camera.png"))
        self.labe_icon_sobre.setObjectName("labe_icon_sobre")
        self.horizontalLayout_5.addWidget(self.labe_icon_sobre)
        self.label_3 = QtWidgets.QLabel(self.frame_qmenu2)
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.bt_maxmize = QtWidgets.QPushButton(self.frame_qmenu2)
        self.bt_maxmize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maxmize.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_maxmize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icone/icons/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maxmize.setIcon(icon1)
        self.bt_maxmize.setIconSize(QtCore.QSize(40, 40))
        self.bt_maxmize.setCheckable(True)
        self.bt_maxmize.setAutoDefault(False)
        self.bt_maxmize.setFlat(True)
        self.bt_maxmize.setObjectName("bt_maxmize")
        self.horizontalLayout_5.addWidget(self.bt_maxmize)
        self.bt_close = QtWidgets.QPushButton(self.frame_qmenu2)
        self.bt_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_close.setAutoFillBackground(False)
        self.bt_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icone/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon2)
        self.bt_close.setIconSize(QtCore.QSize(40, 40))
        self.bt_close.setAutoDefault(False)
        self.bt_close.setDefault(False)
        self.bt_close.setFlat(False)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_5.addWidget(self.bt_close)
        self.verticalLayout.addWidget(self.frame_qmenu2)
        self.frame_menu = QtWidgets.QFrame(Form)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_menu.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_menu.setStyleSheet("QPushButton{\n"
"border:none;\n"
"color:white;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 170, 0);\n"
"\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.botao_menu = QtWidgets.QPushButton(self.frame_menu)
        self.botao_menu.setMinimumSize(QtCore.QSize(180, 0))
        self.botao_menu.setSizeIncrement(QtCore.QSize(0, 0))
        self.botao_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_menu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.botao_menu.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.botao_menu.setStyleSheet("QPushButton{\n"
"    padding:2px 15px;\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icone/icons/cil-arrow-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_menu.setIcon(icon3)
        self.botao_menu.setFlat(True)
        self.botao_menu.setObjectName("botao_menu")
        self.horizontalLayout_7.addWidget(self.botao_menu)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.frame_8 = QtWidgets.QFrame(self.frame_menu)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_TopRight = QtWidgets.QFrame(self.frame_8)
        self.frame_TopRight.setMinimumSize(QtCore.QSize(350, 80))
        self.frame_TopRight.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_TopRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopRight.setObjectName("frame_TopRight")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_TopRight)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_TopAlert = QtWidgets.QFrame(self.frame_TopRight)
        self.frame_TopAlert.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopAlert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopAlert.setObjectName("frame_TopAlert")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_TopAlert)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_TopAlert = QtWidgets.QPushButton(self.frame_TopAlert)
        self.pushButton_TopAlert.setStyleSheet("QPushButton{\n"
"color:#1f3b6f;\n"
"font-weight: bold;\n"
"background-color:transparent;\n"
"font-size:15px;\n"
"border:0px;\n"
"}")
        self.pushButton_TopAlert.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/CYBER/Desktop/Python_PyQt5_DashReceitaFederal-main/assets/img/alert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TopAlert.setIcon(icon4)
        self.pushButton_TopAlert.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_TopAlert.setObjectName("pushButton_TopAlert")
        self.horizontalLayout_9.addWidget(self.pushButton_TopAlert)
        self.resulta_usuario = QtWidgets.QLabel(self.frame_TopAlert)
        self.resulta_usuario.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.resulta_usuario.setStyleSheet("QFrame, QLabel, QToolTip {\n"
"\n"
"    \n"
"    color: rgb(211, 211, 211);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    padding: 2px;\n"
"    \n"
"}")
        self.resulta_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.resulta_usuario.setObjectName("resulta_usuario")
        self.horizontalLayout_9.addWidget(self.resulta_usuario)
        self.horizontalLayout_8.addWidget(self.frame_TopAlert)
        self.frame_TopProfile = QtWidgets.QFrame(self.frame_TopRight)
        self.frame_TopProfile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopProfile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopProfile.setObjectName("frame_TopProfile")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_TopProfile)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_ImgTopProfile = QtWidgets.QPushButton(self.frame_TopProfile)
        self.pushButton_ImgTopProfile.setStyleSheet("QPushButton{\n"
"color:#1f3b6f;\n"
"font-weight: bold;\n"
"background-color:transparent;\n"
"font-size:15px;\n"
"border:0px;\n"
"}")
        self.pushButton_ImgTopProfile.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/CYBER/Desktop/Python_PyQt5_DashReceitaFederal-main/assets/img/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ImgTopProfile.setIcon(icon5)
        self.pushButton_ImgTopProfile.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ImgTopProfile.setObjectName("pushButton_ImgTopProfile")
        self.horizontalLayout_10.addWidget(self.pushButton_ImgTopProfile)
        self.horizontalLayout_8.addWidget(self.frame_TopProfile)
        self.frame_TopDataUser = QtWidgets.QFrame(self.frame_TopRight)
        self.frame_TopDataUser.setMinimumSize(QtCore.QSize(150, 80))
        self.frame_TopDataUser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TopDataUser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TopDataUser.setObjectName("frame_TopDataUser")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_TopDataUser)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_TxtTopDataUser = QtWidgets.QLabel(self.frame_TopDataUser)
        self.label_TxtTopDataUser.setMinimumSize(QtCore.QSize(0, 19))
        self.label_TxtTopDataUser.setStyleSheet("QLabel{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color:#273142;\n"
"\n"
"}")
        self.label_TxtTopDataUser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_TxtTopDataUser.setObjectName("label_TxtTopDataUser")
        self.verticalLayout_5.addWidget(self.label_TxtTopDataUser)
        self.label_TxtTopDataUserType = QtWidgets.QLabel(self.frame_TopDataUser)
        self.label_TxtTopDataUserType.setMinimumSize(QtCore.QSize(0, 25))
        self.label_TxtTopDataUserType.setStyleSheet("QLabel{\n"
"color:#9cb2cd;\n"
"}")
        self.label_TxtTopDataUserType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_TxtTopDataUserType.setObjectName("label_TxtTopDataUserType")
        self.verticalLayout_5.addWidget(self.label_TxtTopDataUserType)
        self.horizontalLayout_8.addWidget(self.frame_TopDataUser)
        self.horizontalLayout_11.addWidget(self.frame_TopRight)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_menu)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_pastas = QtWidgets.QFrame(self.frame_2)
        self.frame_pastas.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_pastas.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_pastas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pastas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pastas.setObjectName("frame_pastas")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_pastas)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pasta = QtWidgets.QTreeView(self.frame_pastas)
        self.pasta.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pasta.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.pasta.setStyleSheet("QTreeView {\n"
"    show-decoration-selected: 1;\n"
"    \n"
"    \n"
"    background-color: rgb(76, 76, 76);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 212, 212);\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    \n"
"    \n"
"     border: 1px solid #d9d9d9;\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"}\n"
"\n"
"QTreeView::item:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e7effd, stop: 1 #cbdaf1);\n"
"    border: 1px solid #bfcde4;\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"    border: 1px solid #567dbc;\n"
"}\n"
"\n"
"QTreeView::item:selected:active{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6ea1f1, stop: 1 #567dbc);\n"
"}\n"
"\n"
"QTreeView::item:selected:!active {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6b9be8, stop: 1 #577fbf);\n"
"}")
        self.pasta.setWordWrap(True)
        self.pasta.setObjectName("pasta")
        self.pasta.header().setDefaultSectionSize(250)
        self.horizontalLayout_3.addWidget(self.pasta)
        self.horizontalLayout_2.addWidget(self.frame_pastas)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setMinimumSize(QtCore.QSize(40, 0))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.widget = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(1080, 800))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setStyleSheet("\n"
"background-color: rgb(199, 199, 199);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.widget)
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setMinimumSize(QtCore.QSize(40, 0))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(250, 800))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_with = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_with.setFont(font)
        self.line_with.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.line_with.setMaxLength(4)
        self.line_with.setAlignment(QtCore.Qt.AlignCenter)
        self.line_with.setObjectName("line_with")
        self.verticalLayout_2.addWidget(self.line_with)
        self.line_2 = QtWidgets.QFrame(self.frame_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_heigt = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_heigt.setFont(font)
        self.line_heigt.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.line_heigt.setMaxLength(4)
        self.line_heigt.setAlignment(QtCore.Qt.AlignCenter)
        self.line_heigt.setObjectName("line_heigt")
        self.verticalLayout_2.addWidget(self.line_heigt)
        self.line_3 = QtWidgets.QFrame(self.frame_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_TxtDataAtual = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_TxtDataAtual.setMinimumSize(QtCore.QSize(190, 50))
        self.lineEdit_TxtDataAtual.setMaximumSize(QtCore.QSize(190, 50))
        self.lineEdit_TxtDataAtual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_TxtDataAtual.setStyleSheet("QLineEdit{\n"
"border-radius:15px;\n"
"background-color: #fff;\n"
"text-align: center;\n"
"font-size:15px;\n"
"color:#273142;\n"
"border:1px solid #e1e4ed;\n"
"text-aling:center;\n"
"}")
        self.lineEdit_TxtDataAtual.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_TxtDataAtual.setObjectName("lineEdit_TxtDataAtual")
        self.verticalLayout_4.addWidget(self.lineEdit_TxtDataAtual)
        self.verticalLayout_2.addWidget(self.frame_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.groupBox = QtWidgets.QGroupBox(self.frame_6)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"cursor: pointer;\n"
"color:white;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"text-align: center;\n"
"}\n"
"QRadioButton{\n"
"cursor: pointer;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color:white;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 26px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"   \n"
"    image: url(:/icone/icons/exti.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover {\n"
"    \n"
"    image: url(:/icone/icons/cil-check-circle.png);\n"
"}\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator::checked {\n"
"  \n"
"    image: url(:/icone/icons/cil-check-circle.png);\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator:checked:pressed {\n"
"    \n"
"    image: url(:/icone/icons/cil-hand-point-up.png);\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_png = QtWidgets.QRadioButton(self.groupBox)
        self.button_png.setStyleSheet("")
        self.button_png.setCheckable(True)
        self.button_png.setChecked(False)
        self.button_png.setAutoExclusive(True)
        self.button_png.setObjectName("button_png")
        self.verticalLayout_3.addWidget(self.button_png)
        self.button_jpg = QtWidgets.QRadioButton(self.groupBox)
        self.button_jpg.setObjectName("button_jpg")
        self.verticalLayout_3.addWidget(self.button_jpg)
        self.button_icon = QtWidgets.QRadioButton(self.groupBox)
        self.button_icon.setObjectName("button_icon")
        self.verticalLayout_3.addWidget(self.button_icon)
        self.button_jpeg = QtWidgets.QRadioButton(self.groupBox)
        self.button_jpeg.setObjectName("button_jpeg")
        self.verticalLayout_3.addWidget(self.button_jpeg)
        self.button_bmp = QtWidgets.QRadioButton(self.groupBox)
        self.button_bmp.setObjectName("button_bmp")
        self.verticalLayout_3.addWidget(self.button_bmp)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("QLineEdit{\n"
"padding:1px500px;\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(900, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.bt_Visualisar = QtWidgets.QPushButton(self.frame)
        self.bt_Visualisar.setMinimumSize(QtCore.QSize(120, 35))
        self.bt_Visualisar.setMaximumSize(QtCore.QSize(0, 50))
        self.bt_Visualisar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.bt_Visualisar.setFont(font)
        self.bt_Visualisar.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.bt_Visualisar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_Visualisar.setStyleSheet("\n"
"QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 137, 206);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon2/icon2/path395.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Visualisar.setIcon(icon6)
        self.bt_Visualisar.setIconSize(QtCore.QSize(40, 60))
        self.bt_Visualisar.setFlat(True)
        self.bt_Visualisar.setObjectName("bt_Visualisar")
        self.horizontalLayout.addWidget(self.bt_Visualisar)
        spacerItem8 = QtWidgets.QSpacerItem(290, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line = QtWidgets.QFrame(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(15)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.verticalLayout.addWidget(self.frame_5)
        self.actionSalva = QtWidgets.QAction(Form)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icone/icons/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalva.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionSalva.setFont(font)
        self.actionSalva.setObjectName("actionSalva")
        self.actionNovo = QtWidgets.QAction(Form)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icone/icons/cil-user-follow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovo.setIcon(icon8)
        self.actionNovo.setObjectName("actionNovo")
        self.actionSave_Pdf = QtWidgets.QAction(Form)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icone/icons/cil-transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Pdf.setIcon(icon9)
        self.actionSave_Pdf.setObjectName("actionSave_Pdf")
        self.actionMenu_Arquivo = QtWidgets.QAction(Form)
        self.actionMenu_Arquivo.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icone/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icone/icons/cil-chevron-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMenu_Arquivo.setIcon(icon10)
        self.actionMenu_Arquivo.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionMenu_Arquivo.setObjectName("actionMenu_Arquivo")
        self.labe_icon_sobre.setBuddy(self.labe_icon_sobre)

        self.retranslateUi(Form)
        self.bt_close.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pasta, self.lineEdit)
        Form.setTabOrder(self.lineEdit, self.bt_Visualisar)
        Form.setTabOrder(self.bt_Visualisar, self.botao_menu)
        Form.setTabOrder(self.botao_menu, self.bt_close)
        Form.setTabOrder(self.bt_close, self.line_with)
        Form.setTabOrder(self.line_with, self.bt_maxmize)
        Form.setTabOrder(self.bt_maxmize, self.line_heigt)
        Form.setTabOrder(self.line_heigt, self.button_png)
        Form.setTabOrder(self.button_png, self.button_jpg)
        Form.setTabOrder(self.button_jpg, self.button_icon)
        Form.setTabOrder(self.button_icon, self.button_jpeg)
        Form.setTabOrder(self.button_jpeg, self.button_bmp)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Carregar Fotos"))
        self.label_3.setText(_translate("Form", "Sistema Carregamento Fotos"))
        self.botao_menu.setText(_translate("Form", "Arquivo"))
        self.resulta_usuario.setToolTip(_translate("Form", "Quantidade De Login Logado"))
        self.resulta_usuario.setText(_translate("Form", "{0}"))
        self.label_TxtTopDataUser.setText(_translate("Form", "{USER}"))
        self.label_TxtTopDataUserType.setText(_translate("Form", "{PROFILE_TYPE}"))
        self.label.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Double Click Open Aba photo/ Dois click abrer pagina foto</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "Width"))
        self.line_with.setInputMask(_translate("Form", "0000"))
        self.line_with.setText(_translate("Form", "1080"))
        self.line_with.setPlaceholderText(_translate("Form", "Width"))
        self.label_2.setText(_translate("Form", "Height"))
        self.line_heigt.setInputMask(_translate("Form", "0000"))
        self.line_heigt.setText(_translate("Form", "1080"))
        self.line_heigt.setPlaceholderText(_translate("Form", "Heigth"))
        self.lineEdit_TxtDataAtual.setText(_translate("Form", "{weekday} 00/00/0000"))
        self.groupBox.setTitle(_translate("Form", "Form Photo"))
        self.button_png.setText(_translate("Form", "PNG"))
        self.button_jpg.setText(_translate("Form", "JPG"))
        self.button_icon.setText(_translate("Form", "ICO"))
        self.button_jpeg.setText(_translate("Form", "JPEG"))
        self.button_bmp.setText(_translate("Form", "bmp"))
        self.lineEdit.setToolTip(_translate("Form", "copy and paste path / Copie e cole aqui caminho"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Copy and paste path"))
        self.bt_Visualisar.setText(_translate("Form", "View"))
        self.actionSalva.setText(_translate("Form", "Salva foto"))
        self.actionSalva.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.actionNovo.setText(_translate("Form", "Novo"))
        self.actionNovo.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Novo</span></p></body></html>"))
        self.actionSave_Pdf.setText(_translate("Form", "Save Pdf"))
        self.actionMenu_Arquivo.setText(_translate("Form", "Menu Arquivo"))
import iconesform_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
