# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templadesui/qrcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qr_code(object):
    def setupUi(self, qr_code):
        qr_code.setObjectName("qr_code")
        qr_code.resize(588, 479)
        self.widget = QtWidgets.QWidget(qr_code)
        self.widget.setGeometry(QtCore.QRect(70, 70, 451, 381))
        self.widget.setStyleSheet("background-color: rgb(158, 158, 158);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 421, 361))
        self.label.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(qr_code)
        self.pushButton.setGeometry(QtCore.QRect(510, 40, 40, 40))
        self.pushButton.setSizeIncrement(QtCore.QSize(40, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"background-color: rgb(83, 83, 83);\n"
"border:none;\n"
"border-radius:19px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(206, 206, 206);\n"
"border:none;\n"
"border-radius:19px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(60, 16))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(qr_code)
        self.pushButton.clicked.connect(qr_code.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(qr_code)

    def retranslateUi(self, qr_code):
        _translate = QtCore.QCoreApplication.translate
        qr_code.setWindowTitle(_translate("qr_code", "qrcode"))
        self.label.setText(_translate("qr_code", "TextLabel"))
import iconesform_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qr_code = QtWidgets.QWidget()
    ui = Ui_qr_code()
    ui.setupUi(qr_code)
    qr_code.show()
    sys.exit(app.exec_())
